dotenv: .env

dependencies:
  # - <organisation/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@3.4.2

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.2'

networks:
  development:
    cmd_settings:
      default_balance: 10000